version: '3.7'
#This node contains the services with all of the different containers we're orchestrating here.'
services:
  # This service has been named with the lowercase version of the project name. We could change this name if we wanted to
  globomantics.identityserver:
    # This is the image in use
    image: ${DOCKER_REGISTRY-}globomanticsidentityserver
    # The real meat comes in the build area which defines the context or working directory for the container, and then, the path to the Dockerfile that defines it.
    build:
      context: .
      # This is the path to the Dockerfile that defines it
      dockerfile: Globomantics.IdentityServer/Dockerfile
    environment:
      # This is to make sure that our Application listens on port 5000 to serve requests.
      - ASPNETCORE_URLS=http://*:5000
    ports:
      # I want the host port to be 5000, and that can map to the container port of 5000 which should be listening
      # for the requests based on the environment variable we set.
      - "5000:5000"
