version: '3.4'
#This node contains the services with all of the different containers we're orchestrating here.'
services:
  globomantics.identityserver: #← This service has been named with the lowercase version of the project name. We could change this name if we wanted to
    image: ${DOCKER_REGISTRY-}globomanticsidentityserver #← This is the image in use
    build:
      context: .
      dockerfile: Globomantics.IdentityServer/Dockerfile #← This is the path to the Dockerfile that defines it
